services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:
      hapi.fhir.server_address: "http://proxy:4180"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-fhir-postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
    ports:
      - "8080:8080"
    networks:
      - hapi-network

  hapi-fhir-postgres:
    image: postgres:15-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      - hapi-network
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data

  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=secretsecretsecr
      - OAUTH2_PROXY_CLIENT_ID=fhir-client
      - OAUTH2_PROXY_CLIENT_SECRET=secret
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAMS=http://host.docker.internal:8080
      - OAUTH2_PROXY_LOGIN_URL=http://host.docker.internal:7070/realms/fhir-realm/protocol/openid-connect/auth
      - OAUTH2_PROXY_REDEEM_URL=http://host.docker.internal:7070/realms/fhir-realm/protocol/openid-connect/token
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://host.docker.internal:7070/realms/fhir-realm
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_SCOPE=openid email profile
      - OAUTH2_PROXY_EMAIL_CLAIM=email
      - OAUTH2_PROXY_OIDC_JWKS_URL=http://host.docker.internal:7070/realms/fhir-realm/protocol/openid-connect/certs
      - OAUTH2_PROXY_SKIP_OIDC_DISCOVERY=false
      - OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS=true
      - OAUTH2_PROXY_REDIRECT_URL=http://host.docker.internal:8080/
      - OAUTH2_PROXY_COOKIE_REFRESH=0s
      - OAUTH2_PROXY_COOKIE_EXPIRE=0s
    networks:
      - hapi-network

volumes:
  hapi-fhir-postgres:

networks:
  hapi-network:
    driver: bridge